### ISSUE TITLE
Keyerror : 'node id' can't generate urd files

### ISSUE THREAD

**Issue by mamKhater** [robotology/simmechanics-to-urdf#40]
Traceback (most recent call last):
  File "/usr/local/bin/simmechanics_to_urdf", line 9, in <module>
    load_entry_point('simmechanics-to-urdf==0.2', 'console_scripts', 'simmechanics_to_urdf')()
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 1871, in main
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 166, in convert
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 497, in parse
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 497, in parse
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 497, in parse
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 497, in parse
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 494, in parse
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 588, in parseFrames
KeyError: 'nodeID'

can't generate URDF files and this is the error shown. this a first gen file from matlab15a and inventor2020

**Comment by traversaro** [comment]
Hi @mamKhater , can you try to change line 588 from:
~~~
            if fdict['nodeID'].endswith('(USERADDED)'):
~~~
to 
~~~
            if 'nodeID' in fdict and fdict['nodeID'].endswith('(USERADDED)'):
~~~
?

**Comment by traversaro** [comment]
Hi @mamKhater , is this still a problem for you?

**Comment by traversaro** [comment]
If you still have this problem @mamKhater , feel free to open a new issue, thanks!
