### ISSUE TITLE
AttributeError: 'Robot' object has no attribute 'version'

### ISSUE THREAD

**Issue by GiovanniBorre** [robotology/simmechanics-to-urdf#41]
Hello, i'm trying to run the [leg mechanism example](https://github.com/robotology/simmechanics-to-urdf/blob/master/test/LEGS_MECHANISM.xml) using this command:

`simmechanics_to_urdf LEGS_MECHANISM.xml --output xml`

but i get an error about the attribute version from the robot. I could't find nothing similar in the `issues.

`Traceback (most recent call last):
  File "/usr/local/bin/simmechanics_to_urdf", line 11, in <module>
    load_entry_point('simmechanics-to-urdf==0.2', 'console_scripts', 'simmechanics_to_urdf')()
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 1871, in main
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 175, in convert
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 202, in generateXML
  File "/opt/ros/melodic/lib/python2.7/dist-packages/urdf_parser_py/xml_reflection/core.py", line 584, in to_xml
    self.write_xml(doc)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/urdf_parser_py/xml_reflection/core.py", line 577, in write_xml
    self.XML_REFL.add_to_xml(self, node)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/urdf_parser_py/xml_reflection/core.py", line 550, in add_to_xml
    attribute.add_to_xml(obj, node)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/urdf_parser_py/xml_reflection/core.py", line 332, in add_to_xml
    value = getattr(obj, self.var)
AttributeError: 'Robot' object has no attribute 'version'`

Thanks

**Comment by daniel-dsouza** [comment]
I believe this is related to https://github.com/ros/urdf_parser_py/issues/59

**Comment by traversaro** [comment]
Hi @GiovanniBorre and @daniel-dsouza , sorry for the late reply. As @daniel-dsouza mentioned, this is an upstream `urdf_parser_py` issue. I will leave the issue open until it is fully solved by urdf_parser_py, in the meanwhile if you want to have a reference for a checkout of urdf_parser_py that is working correctly, you can refer to https://github.com/robotology/icub-model-generator/blob/3d61348ded9390e7d0e31057ebd09f8f439f7357/.travis.yml#L57 that is the checkout we actually use for generation of iCub robot models. 

cc @Nicogene

**Comment by traversaro** [comment]
Related comment in another issue: https://github.com/robotology/simmechanics-to-urdf/issues/36#issuecomment-632715233 .

**Comment by Nicogene** [comment]
Btw the CI is failing for the same reason https://travis-ci.org/github/robotology/simmechanics-to-urdf/jobs/741344160
